### ISSUE TITLE
Init error when loading handler lambda.handler -- cannot load such file -- rack

### ISSUE THREAD

**Issue by denishaskin** [aws-samples/serverless-sinatra-sample#10]
I followed the deployment instructions (here and https://aws.amazon.com/blogs/compute/announcing-ruby-support-for-aws-lambda/, the Sinatra section -- they seem to match).

But when I try to access any of the endpoints of this sample app, I get Internal Server Error.  The lambda cloudwatch logs are:

```
START RequestId: 1f7fc4ff-12d2-11e9-8098-a1246657e2c7 Version: $LATEST
Init error when loading handler lambda.handler
{
"errorMessage": "cannot load such file -- rack",
"errorType": "Init<LoadError>",
"stackTrace": [
"/var/lang/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'",
"/var/lang/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'",
"/var/task/lambda.rb:17:in `<top (required)>'",
"/var/lang/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'",
"/var/lang/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'"
]
}
END RequestId: 1f7fc4ff-12d2-11e9-8098-a1246657e2c7
REPORT RequestId: 1f7fc4ff-12d2-11e9-8098-a1246657e2c7	Duration: 384.13 ms	Billed Duration: 400 ms Memory Size: 512 MB	Max Memory Used: 18 MB	
Unknown application error occurred
Init<LoadError>
```

I suspect I missed something obvious, but I can't find it.

I made *no* modifications to the code in this project.  I cloned it and then:

```
bundle install
bundle install --deployment
brew tap aws/tap
brew install aws-sam-cli
aws s3 mb s3://hh-pr-status
sam package --template-file template.yaml \
   --output-template-file packaged-template.yaml \
   --s3-bucket hh-pr-status
sam deploy --template-file packaged-template.yaml \
   --stack-name LambdaSinatra \
   --capabilities CAPABILITY_IAM
```

**Comment by xiangshen-dk** [comment]
What is the version of your Ruby when you run bundle install? It could be incompatible gems in the package. If you want to just try the application, there is a CloudFormation template(pipeline-cfn.yaml) in the repo. If you create a CloudFormation stack using that template, it will build and deploy the app for you.

**Comment by denishaskin** [comment]
Yup, that was it, I was on ruby 2.4.x.  I thought `rvm` was defaulting to 2.5.  All works as expected now that I've switched to ruby 2.5.

**Comment by bethesque** [comment]
This got me too. It's worth adding to the README. Will raise a PR if I have a moment.
