### ISSUE TITLE
How do I run this application in my local environment? 

### ISSUE THREAD

**Issue by vasudharsai** [aws-samples/serverless-sinatra-sample#21]
I was looking for steps to set this application in my local environment at localhost:3000. So that I can first enhance and test changes in my local environment before deploying it to AWS.

Any steps explaining the above would be greatly helpful

**Comment by xiangshen-dk** [comment]
You can use the SAM CLI to run the application locally. 

SAM CLI: https://github.com/awslabs/aws-sam-cli

Useful example: http://aws-cloud.guru/testing-lambdas-locally-with-aws-sam-cli/

After you install SAM CLI, you can run __sam local start-api__ to start the API at your local environment.

**Comment by vasudharsai** [comment]
Thank you so much for the info. The project helped me to understand how to setup a sinatra application with serverless framework
