### ISSUE TITLE
Feature request: Publish lambda.rb under copyright-free license 

### ISSUE THREAD

**Issue by netkgk** [aws-samples/serverless-sinatra-sample#3]
It is hard to imagine `lambda.rb` rewritten in a such manner it would be substantially different from the one published in this repo. The reason is that `lambda.rb` is sort of API-to-API interface which includes a lot API calls so it will always look as "derivative". As such, it would be nice to have just this one file from this repo under Public Domain or Unlicense.

**Comment by xiangshen-dk** [comment]
Changed the license to "MIT No Attribution" (MIT-0) for `lambda.rb`.
