### ISSUE TITLE
cloud formation stack types and sort of related question

### ISSUE THREAD

**Issue by keithmgould** [aws-samples/serverless-sinatra-sample#7]
Hello!

Thank you for putting this together.

I'm at the step of deploying the app, and I have never used cloud formation before, so I'm not sure what is expected.  Would be nice if in the readme you mentioned what type of stack we should create -- should it be from a template?

Also, I know this is sort of unrelated, but I'm having trouble using Ruby Lambdas when trying to upload a 3rd party GEM.  As in, I'm trying to skip S3, and try just getting the gem recognized in the env. For a really really simple example, 

```
require 'json'
require 'sinatra'

def lambda_handler(event:, context:)
    hsh = { foo: "bar" }
    { statusCode: 200, body: JSON.generate(hsh) }
end
```

I've tried the combo of:

0. bundle install
0. bundle install --deployment
0. zip the directory
0. upload the directory

and the env can never find the `sinatra` gem. Is it necessary to go through the S3 steps? Or do you think i'm missing something? 

Thank you for any thoughts!

**Comment by xiangshen-dk** [comment]
We have a blog post(https://aws.amazon.com/blogs/compute/announcing-ruby-support-for-aws-lambda/) describing how to create a simple Ruby Lambda function with dependencies.

The examples in the blog post used AWS SAM template. However, you don't have to use SAM. You can use `bundle install --deployment` to install the gems and create a zip file. Then you can upload the zip file either via CLI or the console. 

The CloudFormation template **pipeline-cfn.yaml** can be used directly from the CloudFormation console. It will create the sample app with API gateway and the Lambda. A codepipeline will be created as well. If you take a look the template, it's pretty straightforward.

**Comment by keithmgould** [comment]
Thank you.
