### ISSUE TITLE
Possible typo regarding event headers

### ISSUE THREAD

**Issue by travishaynes** [aws-samples/serverless-sinatra-sample#8]
On [this line](https://github.com/aws-samples/serverless-sinatra-sample/blob/master/lambda.rb#L39), there appears to be a typo. It checks if a key named `header` is available in the event, then uses a key named `headers`. Is that intentional?

It also modifies the header values to include an `HTTP_` prefix. Should it not be the key that is modified?

**Comment by xiangshen-dk** [comment]
You are correct. It's fixed. Thanks!
